apiVersion: v2
name: knit-db-postgres
description: knitfab database (postgres)
type: application
keywords:
  - knitfab
  - MLOps
  - Lineage Tracking
  - Workflow
  - Tag Based Workflow

version: ${CHART_VERSION}
appVersion: ${APP_VERSION}
